language: csharp
solution: PhiFailureDetector.sln
dotnet: 1.0.4
mono: none

git:
  depth: 1

before_install:
  - git fetch --unshallow

before_script:
  - dotnet restore

script:
  - dotnet build
  - dotnet test PhiFailureDetector.UnitTest/PhiFailureDetector.UnitTest.csproj
